# SITE CONFIGURATION
title: Jane # your site title
author: Shu Huang# You :P
description: > # Meta description of Homepage
  这是陈静的房间。
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ccchenjing.club/ # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/yellowtreeee
    - https://www.facebook.com/yellowtreee
    - https://github.com/ShuHuang

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: '联系', link: '/contact'}

tagline: >
  无敌可爱的小陈静。

hero_img: posts/jane1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: shu.huang-2@outlook.com # email for form submission

twitter_username: yellowtreeee # replace with your_twitter_username or comment to remove link from footer
github_username:  ShuHuang # replace with your_github_username or comment to remove link from footer
instagram_username: crazyyellowtree # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: shu # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
